### ISSUE TITLE
Not working in my image

### ISSUE THREAD

**Issue by abdulraffi** [viksoffice/CheckDrawnAlphabet_Android#2]
i have made image like your instruction, but paint dosen't show. What wrong whit my image ?

thanks

![a](https://cloud.githubusercontent.com/assets/18075016/24991541/b3855708-2045-11e7-8d28-31a429ee95aa.png)

**Comment by Aishwarya-Surana** [comment]
What helped you? @raffimaut

**Comment by vikskod** [comment]
Please download the code and re check alphabet image carefully.
